import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';

export interface FixSuggestion {
  id: string;
  title: string;
  description: string;
  code: string;
  pros: string[];
  cons: string[];
  difficulty: 'easy' | 'medium' | 'hard';
  recommended: boolean;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { code, language, errorType, errorMessage } = body;

    if (!code) {
      return NextResponse.json(
        { 
          success: false,
          error: 'No code provided',
          code: 'VALIDATION_EMPTY_CODE'
        },
        { status: 400 }
      );
    }

    // Initialize OpenAI client at runtime
    const openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY || '',
    });

    // Build comprehensive prompt for multiple suggestions
    const prompt = buildSuggestionsPrompt(code, language, errorType, errorMessage);

    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: `You are an expert software engineer who provides multiple solution approaches for fixing bugs. For each bug, provide 2-3 different fix suggestions with varying approaches (quick fix, robust fix, optimal fix). Return ONLY a valid JSON array without any markdown formatting or additional text. Each suggestion must have: id, title, description, code, pros (array), cons (array), difficulty (easy/medium/hard), and recommended (boolean).`,
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
      temperature: 0.3,
      max_tokens: 3000,
    });

    const suggestionsText = response.choices[0].message.content || '';
    
    // Parse suggestions from response
    let suggestions: FixSuggestion[];
    try {
      // Clean markdown code blocks if present
      const cleanedText = suggestionsText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
      suggestions = JSON.parse(cleanedText);
    } catch (parseError) {
      console.error('Failed to parse suggestions:', parseError);
      // Fallback: create a single suggestion from the response
      suggestions = [{
        id: 'fallback',
        title: 'AI-Generated Fix',
        description: 'Fixed code generated by AI',
        code: suggestionsText,
        pros: ['AI-optimized solution'],
        cons: ['May need manual review'],
        difficulty: 'medium',
        recommended: true,
      }];
    }

    return NextResponse.json({
      success: true,
      suggestions,
      count: suggestions.length,
      timestamp: new Date().toISOString(),
    });

  } catch (error: unknown) {
    console.error('Generate suggestions error:', error);
    
    let errorMessage = 'Unknown error occurred';
    let errorCode = 'UNKNOWN_ERROR';
    let statusCode = 500;
    
    if (error instanceof Error) {
      errorMessage = error.message;
      
      if (error.message.includes('rate limit') || error.message.includes('429')) {
        errorCode = 'API_RATE_LIMIT';
        errorMessage = 'Rate limit exceeded. Please wait a moment and try again';
        statusCode = 429;
      } else if (error.message.includes('API key') || error.message.includes('401')) {
        errorCode = 'API_KEY_MISSING';
        errorMessage = 'OpenAI API key is not configured properly';
        statusCode = 401;
      }
    }
    
    return NextResponse.json(
      { 
        success: false,
        error: errorMessage,
        code: errorCode,
      },
      { status: statusCode }
    );
  }
}

function buildSuggestionsPrompt(
  code: string,
  language: string = 'python',
  errorType?: string,
  errorMessage?: string
): string {
  let prompt = `Analyze this ${language} code and provide 2-3 different fix suggestions:\n\n\`\`\`${language}\n${code}\n\`\`\`\n\n`;

  if (errorType) {
    prompt += `Error Type: ${errorType}\n`;
  }

  if (errorMessage) {
    prompt += `Error Message: ${errorMessage}\n`;
  }

  prompt += `\nProvide 2-3 different fix approaches:
1. Quick Fix - Fast, minimal changes
2. Robust Fix - Production-ready, includes error handling
3. Optimal Fix - Best practices, performance optimized

Return as JSON array with this exact structure:
[
  {
    "id": "quick",
    "title": "Quick Fix",
    "description": "Brief description",
    "code": "fixed code here",
    "pros": ["advantage 1", "advantage 2"],
    "cons": ["disadvantage 1"],
    "difficulty": "easy",
    "recommended": false
  }
]

IMPORTANT: Return ONLY the JSON array, no markdown, no explanations.`;

  return prompt;
}
